version: '3.3'

services:
  recruitment-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - mysql-db
      - redis
  mysql-db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      #      MYSQL_DATABASE: auth
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql
      - ./job_db.sql:/docker-entrypoint-initdb.d/job_db.sql
    restart: on-failure
  redis:
    image: redis:7.2.1-alpine3.18
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    restart: on-failure
    command: /bin/sh -c "redis-server --requirepass $${REDIS_PASSWORD}"
  prometheus:
    image: prom/prometheus:v2.46.0
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana:10.0.3-ubuntu
    ports:
      - '3000:3000'
    volumes:
      - grafana:/var/lib/grafana
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
volumes:
  mysql-db:
    driver: local
  grafana:
    driver: local